# Generated by Django 3.2.6 on 2021-08-18 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_todo_date_completion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='date_completion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
